### ISSUE TITLE
add an endevour os wallpaper

### ISSUE THREAD

**Issue by gamerseye123** [linuxdotexe/nordic-wallpapers#11]
if youre wondering why i keep asking for wallpapers i switched from windows to zorin os to manjaro and now to endeavour os

**Comment by linuxdotexe** [comment]
[Done!](https://github.com/linuxdotexe/nordic-wallpapers/commit/817ca8cea42a76eadb523b3f39d9fb70e6b6ce95)

> if youre wondering why i keep asking for wallpapers i switched from windows to zorin os to manjaro and now to endeavour os

distro hopping is a great hobby! I used to do that too haha
