### ISSUE TITLE
License Issue and Package Maintainer Request

### ISSUE THREAD

**Issue by zjuyk** [linuxdotexe/nordic-wallpapers#2]
Really a good collection. I am a Nord/Nordic fan too. I'd like to package these wallpapers in Arch Linux. A proper license is required and I think MIT is good enough.

BTW, I am also the ImageGoNord packager in AUR. 

Hint: If you do not know much about open source license, maybe refer to this [post](https://itsfoss.com/open-source-licenses-explained/)

**Comment by zjuyk** [comment]
Done with [this upload](https://aur.archlinux.org/packages/nordic-wallpapers/).

**Comment by linuxdotexe** [comment]
> Done with [this upload](https://aur.archlinux.org/packages/nordic-wallpapers/).

Please update `README.md` with information on how to use the AUR package.

**Comment by zjuyk** [comment]
Alright, I'll make a PR.
