### ISSUE TITLE
need to fix the github actions workflow

### ISSUE THREAD

**Issue by linuxdotexe** [linuxdotexe/nordic-wallpapers#20]
I messed something up in the actions workflow that must add all the wallpapers to the `wallpaper-preview.md` file. Need help with that. PRs are welcome.

**Comment by Artmorse** [comment]
I think that this issue is done ?
Tell me if you need some help on it!

**Comment by linuxdotexe** [comment]
I observed it's been doing what it needs to do but was skeptical so I kept it open. Could you please confirm everything is fine like technically in the actions file so I can close this issue? Thanks a lot for the reply.

**Comment by Artmorse** [comment]
Yes, for me, the action do what you want and apparently its work well like that! :wink:

**Comment by linuxdotexe** [comment]
Closing it then. Thanks and cheers!
