### ISSUE TITLE
Add ImageGoNord link in GitHub repo description 

### ISSUE THREAD

**Issue by TheJoin95** [linuxdotexe/nordic-wallpapers#24]
Hi, I'm the dev behind ImageGoNord, is it possible to add also the ImageGoNord link into the GitHub repo description?

I see a lot of people is using our service (self hosted on a OVH instance) but a lot of them are not giving us any credits

It makes us happy see the community uses our tool but also sad when we are reading some missleading information around the web

Enforcing the tool via a link or a note or a post would be great for us!

p.s. it's an open source project, any help would be appreciated, we put our money, our time and our skills to build and maintain it :)

Thank you

**Comment by linuxdotexe** [comment]
Sure! It's in the README and I'll add it to the description too. Thanks a lot for your amazing work :heart:

I will do the following as a token of gratitude and close this issue after all these are complete:

- [ ] add a section about your work in the README
- [ ] add a link to all your sponser pages
- [ ] write an article on my blog when I get time (it doesn't really have much audience though)

Please let me know if it is possible to host another instance of ImageGoNord or help you scale in any way. I will add how it can be done that to the README so if anyone is interested, they can help.

**Comment by TheJoin95** [comment]
Thank you for all these actions!

We are now looking for sponsor in order to create a new conversion algorithm (by adding deep learning), that would be super because we have some good plans for the community (tshirt, stickers and many more); anyone can host an instance of ImageGoNord but we preferred to manage our instance by ourselves because we can optimize or do some experiments in order to get the best results!

Feel free to reach us out :)

**Comment by linuxdotexe** [comment]
kinda irrelevant side note, if you ever need lofi-ish music for any podcasts or other content, check out my stuff:)

here is a link: [sai nivas mangu](https://open.spotify.com/artist/0Gxw6n8Pfk3ZVbgMhvu0zd?si=JcKK2-g6TJihip7vAHejXA)

**Comment by TheJoin95** [comment]
Thanks for your link, it's really nice

I also add you here our links to the [wallpaper page](https://ign.schrodinger-hat.it/wallpaper) and to our [subreddit community ](https://reddit.com/r/imagegonord/) where you can find even more wallpapers! Maybe we can make you moderator of that subreddit, where we convert any sort of image by giving also the credits to the author in the first comment. 

I mean, maybe we can work together and centralize the wallpaper directory, what do you think?

**Comment by linuxdotexe** [comment]
Thanks for the opportunity! Can we take this conversation to any chat platform?
