### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by jampopoy** [linuxdotexe/nordic-wallpapers#30]
Hi just bump into these and saw your wallpaper outputs. may I know what are your settings while using ImageGoNord? I used it on my own wallpapers i want but the out put is not good as yours. Would really be a big of help if you give me your own settings as well. Thanks in advance.

**Comment by linuxdotexe** [comment]
I just use the website. I turn these on and the output comes out great. But I guess you can check out if the [ImageGoNord](https://github.com/Schrodinger-Hat/ImageGoNord) repo has any docs.

![image](https://user-images.githubusercontent.com/74004229/224511452-2d944af7-916c-43a3-a1f0-63271c8477e9.png)
