### ISSUE TITLE
No Zorin OS Wallpaper

### ISSUE THREAD

**Issue by gamerseye123** [linuxdotexe/nordic-wallpapers#4]
now that there is distro specific versions of the same wallpaper, please add a Zorin OS wallpaper

**Comment by linuxdotexe** [comment]
[done!](https://github.com/linuxdotexe/nordic-wallpapers/commit/504e0ea439e04bff1117dd0879a44b88d79a3130)

**Comment by gamerseye123** [comment]
thanks mate btw if possible can you add an android one?

**Comment by linuxdotexe** [comment]
> thanks mate btw if possible can you add an android one?

like a mobile wallpaper or desktop resolution?
